name = "cloud-gallery"
compatibility_date = "2024-04-03"
pages_build_output_dir = "dist"

[[r2_buckets]]
binding = "R2"
bucket_name = "cloudgallery"

[[r2_buckets]]
binding = "CHAT_R2"
bucket_name = "cloud-gallery-chat"

[[d1_databases]]
binding = "DB"
database_name = "guarly"
database_id = "6ee35aec-ac66-4fcb-ac12-4de74213d21c"


